-- MySQL Script generated by MySQL Workbench
-- Fri Oct  1 11:40:01 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ventas` (
  `idVentas` INT NOT NULL,
  `idVehiculos` VARCHAR(8) NULL,
  `idUsers` VARCHAR(6) NULL,
  `DUIcomprador` VARCHAR(10) NULL,
  `Fecha` DATE NULL,
  `Valor` VARCHAR(7) NULL,
  `Tipodepago` VARCHAR(18) NULL,
  `Metododepago` VARCHAR(15) NULL,
  PRIMARY KEY (`idVentas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `idUsers` VARCHAR(6) NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Apellido` VARCHAR(45) NULL,
  `NombreUsuario` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `DUI` VARCHAR(45) NULL,
  `Puesto` VARCHAR(45) NULL,
  `Rol` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsers`),
  CONSTRAINT `fk_Users_Ventas`
    FOREIGN KEY (`idUsers`)
    REFERENCES `mydb`.`Ventas` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vehiculos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vehiculos` (
  `idVehiculos` VARCHAR(8) NOT NULL,
  `Marca` VARCHAR(45) NULL,
  `Modelo` VARCHAR(45) NULL,
  `Year` DATE NULL,
  `Recorrido` INT NULL,
  `Vehiculoscol` VARCHAR(45) NULL,
  `Motor` INT NULL,
  `Puertas` INT NULL,
  `Tipo` VARCHAR(45) NULL,
  `Precio` DECIMAL(7) NULL,
  `Transmision` VARCHAR(45) NULL,
  PRIMARY KEY (`idVehiculos`),
  CONSTRAINT `fk_Vehiculos_Ventas1`
    FOREIGN KEY (`idVehiculos`)
    REFERENCES `mydb`.`Ventas` (`idVehiculos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
